Reset ball filter
bit-bots/bitbots_world_model pull request #19
Opened 2021-06-23 20:58 UTC by jaagut

## Proposed changes
Adds a service to enable resetting the ball filter (as necessary for the behavior)

## Related issues
bit-bots/bitbots_behavior/pull/233

## Necessary checks
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

2021-06-23 21:02 UTC, NFiedler requested changes
Use a trigger service instead of a custom one

2021-06-25 10:10 UTC, SammyRamone approved these changes, later dismissed

2021-06-25 10:40 UTC, johagge approved these changes
i tested it and it works well

2021-06-25 10:41 UTC, NFiedler approved these changes

2021-06-25 10:42 UTC, merged