Fix ros2 ball filter
bit-bots/bitbots_world_model pull request #28
Opened 2022-04-26 15:09 UTC by val-ba

## Proposed changes
- reintroduce necessary outcommented line
- add test script

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

2022-05-03 17:43 UTC, Flova requested changes

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +        self.get_logger().warning("init")
Remove debug warning

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +        self.get_logger().warning("dynamic reconfigure")
Same here

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +        self.get_logger().warning("Ball callback")
Same here

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +    def ball_callback(self, msg: PoseWithCertaintyArray, optional_distance=True):
what does `optional_distance=True` do?

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +
Only one line between functions in a class

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +        self.get_logger().warning("reset filter calback")
Same here

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +        self.get_logger().warning("init filter")
Same here

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_filter.py
> +
Same here

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_publisher.py
> +
One line

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_publisher.py
> +
Two lines

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_publisher.py
> +import math
Maybe merge `ball_publisher.py` and `ball_sim.py`

2022-05-03 17:43 UTC, Flova commented on bitbots_ball_filter/scripts/ball_sim.py
> +        rclpy.init(args=sys.argv)
Missing `rclpy.spin()`, so callback/time/... do not work. See `ball_publisher.py` for correct usage.

2022-05-03 17:44 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_publisher.py
> +import math
Opinions @val-ba @kindlingAsh ?

2022-05-11 14:29 UTC, Flova commented on bitbots_ball_filter/bitbots_ball_filter/ball_publisher.py
> +import math
Not necessarily relevant for this review, but what do you think?

2022-05-11 19:26 UTC, Flova commented on bitbots_ball_filter/scripts/ball_sim.py
> +    rclpy.spin(SimBall())
This should work, but the standard format looks like this:

https://github.com/bit-bots/bitbots_world_model/blob/47e8de43abaab5bdb3f6aa8d85c61078f5e4e494/bitbots_ball_filter/bitbots_ball_filter/ball_filter.py#L258

2022-05-19 14:48 UTC, jaagut commented
Closes #27

2022-05-20 17:05 UTC, Flova approved these changes

2022-05-20 17:05 UTC, merged