Create ball filter
bit-bots/bitbots_world_model pull request #3
Opened 2021-01-07 16:23 UTC by NFiedler

Creates a new Kalman filter based ball filter.

2021-03-29 15:11 UTC, NFiedler commented
The parameters and integration of the stuff into the behavior are not included. this is just about putting some filter there which actually filters the ball in a somewhat reasonable manner.

2021-04-15 14:23 UTC, SammyRamone approved these changes, later dismissed
lgtm but didnt test

2021-04-15 14:53 UTC, timonegk commented on bitbots_ball_filter/src/bitbots_ball_filter/ball_filter.py
> +        # TODO: paramter
There is still a todo here

2021-04-15 15:22 UTC, timonegk requested changes

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/package.xml
> +  <!--   <doc_depend>doxygen</doc_depend> -->
Clean up boilerplate

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/CMakeLists.txt
> +## System dependencies are found with CMake's conventions
Please remove the lines that are not needed to make the file more readable.

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/scripts/ball_sim.py
> +        rospy.sleep(1)
Is this line necessary?

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/scripts/ball_sim.py
> +            rospy.sleep(self.dt)
Use a `rospy.Rate` instead of this

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/scripts/ball_sim.py
> +SimBall()
```suggestion
if __name__ == '__main__':
    SimBall()
```

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/src/bitbots_ball_filter/ball_filter.py
> +            """
```suggestion
        """"
        When ball has been assigned a value and filter has been initialized:
        state will be updated according to filter.
        If filter has not been initialized, then that will be done first.

        If there is not data for ball, a prediction will still be made and published
        Process noise is taken into account
        """
```

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/src/bitbots_ball_filter/ball_filter.py
> +                self.publish_data(*state)
In the if-branches above, you could move common parts outside of the branches.

2021-04-15 15:22 UTC, timonegk commented on bitbots_ball_filter/src/bitbots_ball_filter/ball_filter.py
> +                             [0.0, 0.0, 0.0, 1.0]])
Where do these values come from?

2021-04-15 15:57 UTC, Flova submitted a review, later dismissed
I tested this pr and it works

2021-04-23 12:32 UTC, timonegk approved these changes

2021-04-27 09:26 UTC, merged